import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "wekids",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`antialiased`}>
        <div className="wrapper">{children}</div>
      </body>
    </html>
  );
}
